server:
  port: 8080

spring:
  datasource:
    url: libsql://mahjong-liushiud.aws-ap-northeast-1.turso.io
    username: ""
    password: eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3NjA5NjMwNTcsImlkIjoiZDY2NWQzZTUtODViNi00YjViLTg4MzktMmQzMTFmZTliYWJiIiwicmlkIjoiZmYzNDllMDgtYzcwZC00Mjg2LTkxYWUtYzI1NTQ1NjNjNmFkIn0.NHYTE-yxyLaVe74Zi7EtYBRLJFiXbixg9OvrE7Gtu6WhXEQMbGJICrdeMJLBzJFx_PvEh437OupQoqsMUiDeAQ
    driver-class-name: com.dbeaver.jdbc.driver.libsql.LibSqlDriver
    type: org.springframework.jdbc.datasource.SimpleDriverDataSource
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

line.bot:
  channel-token: ltryhCt6Pk0E40zVQ+C8hKPraZQXaJIzYWiFDKynzGRubpcTh31tmLIw0JYgO/p4P4Q3Jovq6DK9YPjySGRLHXn0mn69yY0h7AqwYI/nDswutjBFE+dZCQVYadnzPs5Yojc1aFpA08g0nFJ+imTa2AdB04t89/1O/w1cDnyilFU=
  channel-secret: 2f743b425967ed382d87b1fd7672cd96
